# Generated by Django 5.2.3 on 2025-07-04 21:03

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر دسته بندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کوپن')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='درصد تخفیف (مثلا ۱۰ برای ۱۰ درصد)', null=True, verbose_name='درصد تخفیف')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='مبلغ ثابت تخفیف به تومان', max_digits=10, null=True, verbose_name='مبلغ تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از تاریخ')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='محدودیت تعداد استفاده (برای هر کاربر)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده شده')),
                ('min_cart_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حداقل مبلغ سبد برای اعمال')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='حداکثر مبلغ تخفیف قابل اعمال (اگر درصد باشد)', max_digits=10, null=True, verbose_name='حداکثر مبلغ تخفیف')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='سایز')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=shop.models.upload_to, verbose_name='تصویر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street', models.CharField(max_length=255, verbose_name='خیابان/کوچه')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='نام گیرنده')),
                ('recipient_phone_number', models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی (مثلاً پلاک، واحد)')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش فرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کلید نشست (برای کاربران مهمان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ کل سفارش')),
                ('shipping_method', models.CharField(choices=[('free_delivery', 'ارسال رایگان'), ('post_office', 'پست پیشتاز')], default='free_delivery', max_length=50, verbose_name='روش ارسال')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد پیگیری')),
                ('coupon_used_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد کوپن استفاده شده')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.address', verbose_name='آدرس ارسال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('fixed_discount_percentage', models.PositiveIntegerField(default=0, help_text='درصد تخفیف ثابت برای کل محصول (۰ تا ۱۰۰). در صورت فعال بودن تخفیف زمان\u200cدار، این اعمال نمی\u200cشود.', verbose_name='تخفیف ثابت (%)')),
                ('timed_discount_percentage', models.PositiveIntegerField(default=0, help_text='درصد تخفیف زمان\u200cدار (۰ تا ۱۰۰)', verbose_name='تخفیف زمان\u200cدار (%)')),
                ('timed_discount_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع تخفیف زمان\u200cدار')),
                ('timed_discount_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخفیف زمان\u200cدار')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, to='shop.tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد کل بسته')),
                ('color_image', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to, verbose_name='تصویر رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'بسته محصول (رنگ)',
                'verbose_name_plural': 'بسته\u200cهای محصول (رنگ)',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت واحد (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی کل')),
                ('online_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی آنلاین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع محصولات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price_at_order', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت هنگام سفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='سفارش')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price_at_addition', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت هنگام اضافه شدن')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='سبد خرید')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه (تومان)')),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='shop.productbatch', verbose_name='بسته محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'تعداد موجودی سایز',
                'verbose_name_plural': 'تعداد موجودی سایزها',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.sizequantity', verbose_name='تعداد موجودی سایز'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('product', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='sizequantity',
            unique_together={('product_batch', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
