# Generated by Django 5.2.3 on 2025-06-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='درصد تخفیف (0 تا 100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='برچسب فروش ویژه برای این محصول؟'),
        ),
    ]
