# Generated by Django 5.2.3 on 2025-06-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_tag_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='موجودی کل'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('total_quantity', models.PositiveIntegerField(help_text='تعداد کل بسته')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(choices=[(32, 32), (34, 34), (36, 36), (38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62)])),
                ('quantity', models.PositiveIntegerField(help_text='تعداد این سایز')),
                ('price', models.DecimalField(decimal_places=2, help_text='قیمت هر واحد', max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='shop.productbatch')),
            ],
        ),
    ]
