# Generated by Django 5.2.3 on 2025-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_productvariant_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='online_stock',
            field=models.PositiveIntegerField(default=0, help_text='موجودی قابل فروش آنلاین (قابل تغییر دستی)'),
        ),
    ]
