# Generated by Django 5.2.3 on 2025-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fixed_discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='تخفیف ثابت بدون محدودیت زمانی (درصد)'),
        ),
        migrations.AddField(
            model_name='product',
            name='timed_discount',
            field=models.JSONField(blank=True, default=dict, help_text='تخفیف زمان\u200cدار شامل start_date, end_date, و percentage', null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
