# Generated by Django 5.2.3 on 2025-06-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_fixed_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_special_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timed_discount',
        ),
        migrations.CreateModel(
            name='TimedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='تاریخ شروع (شمسی، فرمت: 1404-04-04 13:00)')),
                ('end_date', models.DateTimeField(help_text='تاریخ پایان (شمسی، فرمت: 1404-04-05 13:00)')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='درصد تخفیف (0 تا 100)', max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_discounts', to='shop.product')),
            ],
        ),
    ]
