# Generated by Django 5.2.3 on 2025-06-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_is_special_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timed_discount_end_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ پایان تخفیف زمان\u200cدار (شمسی، فرمت: 1404-04-05 13:00)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timed_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد تخفیف زمان\u200cدار (0 تا 100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timed_discount_start_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ شروع تخفیف زمان\u200cدار (شمسی، فرمت: 1404-04-04 13:00)', null=True),
        ),
        migrations.DeleteModel(
            name='TimedDiscount',
        ),
    ]
