# Generated by Django 5.2.3 on 2025-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_timed_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fixed_discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='تخفیف ثابت بدون محدودیت زمانی (درصد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='timed_discount_end_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ پایان تخفیف زمان\u200cدار (میلادی، فرمت: 2025-06-26 18:00)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='timed_discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='درصد تخفیف زمان\u200cدار (0 تا 100)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='timed_discount_start_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ شروع تخفیف زمان\u200cدار (میلادی، فرمت: 2025-06-25 18:00)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='price',
            field=models.PositiveIntegerField(help_text='قیمت هر واحد'),
        ),
    ]
